name: Maven CI
on: pull_request

jobs:
  mvn-tests:
    name: "Run maven compile and tests"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            redis-version: [6, 7]
    steps:

    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Maven test
      run: mvn -B test
